#
#                GLWT(Good Luck With That) Public License
#                  Copyright (c) Everyone, except Author
# 
# Everyone is permitted to copy, distribute, modify, merge, sell, publish,
# sublicense or whatever they want with this software but at their OWN RISK.
# 
#                             Preamble
# 
# The author has absolutely no clue what the code in this project does.
# It might just work or not, there is no third option.
# 
# 
#                 GOOD LUCK WITH THAT PUBLIC LICENSE
#    TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION, AND MODIFICATION
# 
#   0. You just DO WHATEVER YOU WANT TO as long as you NEVER LEAVE A
# TRACE TO TRACK THE AUTHOR of the original product to blame for or hold
# responsible.
# 
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
# 
# Good luck and Godspeed.
#
# WeatherControl config

# General settings
# Verbose ? If true, console will log information and users with wc.verbose permission will receive messages about WeatherEvents.
verbose: false

# Is rain enabled ?
rain-enabled: true
# Are storms enabled ?
storms-enabled: true
# Lightning strikes enabled ?
lightning-enabled: true

# Use custom weather or vanilla weather ?
custom-weather: false


# Vanilla weather settings
# limit-method :
# - rand    : Uses rain-frequency and storms-frequency to randomly lower rain/storms probability.
# - ticks   : Uses rain-ticks and storms-ticks to enforce a mandatory waiting time before the weather can turn bad again.
limit-method: rand

# Rain probability. 1 = 100% = default.
rain-frequency: 1
# Storm probability. 1 = 100% = default.
storms-frequency: 1
# Ligthning strikes frequency. 1 = 100% = default;

# Minimum ticks after last rain before it can rain again.
rain-ticks: 48000
# Minimum ticks after last storm before it can storm again.
storms-ticks: 96000
# Minimum ticks before lightning can strike again.
lightning-ticks: 300


# Custom weather settings
# Minimum rain duration in ticks.
rain-duration: 6000
# Minimum storm duration in ticks.
storms-duration: 6000
